### ISSUE TITLE
Unable to load AWSCognito in Lambda

### ISSUE THREAD

**Issue by Patrax** [aws/amazon-cognito-identity-js#149]
I'm trying to move my auth code into a Lambda. But I keep getting undefined errors. I've tried:

```
/** All versions bundling with Webpack and without **/
var AWS = require('aws-sdk'); // Tried 'aws-sdk/dist/aws-sdk' too
var AWSCognito = require('amazon-cognito-identity-js'); // Tried var cognito = ... too
```

I can access `new AWS.CognitoIdentityCredentials` from the AWS object which is good.
But I can never seem to load AWSCognito to use

```
new AWSCognito.CognitoUserPool
new AWSCognito.AuthenticationDetails
new AWSCognito.CognitoUser
```

I'm using the webpack.config.js file from the README:

```
var AWS_SDK_BUNDLE = 'amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js';

module.exports = {
  // Example setup for your project:
  // The entry module that requires or imports the rest of your project.
  // Must start with `./`!
  entry: './functions/session',
  // Place output files in `./dist/my-app.js`
  output: {
    path: 'dist',
    filename: 'session.js'
  },
  // ... other configuration

  // The current version of the AWS SDK for JavaScript does not work without extra configuration
  // under webpack, see https://github.com/aws/aws-sdk-js/issues/603.
  // This configuration uses the packaged output file as it is simple, see the issue for other
  // options with different tradeoffs.
  resolve: {
    alias: {
      'aws-sdk$': AWS_SDK_BUNDLE
    }
  },
  module: {
    noParse: /aws-cognito-sdk/,
    // Optional, but makes debugging library code much nicer:
    preLoaders: [
      {
        test: /\.min\.js$/,
        loader: 'source-map'
      }
    ],
    loaders: [
      {
        test: require.resolve(AWS_SDK_BUNDLE),
        loader: 'exports?AWSCognito'
      }
    ]
  }
};
```

**Comment by itrestian** [comment]
I don't see any problem by looking at your code. Does this work in your development environment or it happens only when uploading to lambda?

**Comment by Patrax** [comment]
It only happens when uploading to Lambda. I'm using Serverless Framework to manage the deploy.

**Comment by Patrax** [comment]
If instead I do (without using Webpack):

```
var AWS = require('aws-sdk');
AWS.util.isBrowser = function() { return false; };
var cognito = require('amazon-cognito-identity-js');
```

Then I only get a window is not defined error in `amazon-cognito-identity-js` which could be a step forward:

```
2016-09-21T14:30:18.610Z    e9a9e299-8007-11e6-91a8-d5b11a1bf064    ReferenceError: window is not defined
at e.o.value (/var/task/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js:19:22434)
at Response.<anonymous> (/var/task/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js:19:11042)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:355:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by simonbuchan** [comment]
Possibly an issue with pre #140 cognito-sdk talking to post 2.6.0 aws-sdk?

@Patrax if you `npm up aws-sdk` on your local do you start getting the same issue? Does `npm up amazon-cognito-identity-js` fix the issue now that #140 is merged?

**Comment by simonbuchan** [comment]
The `window is not defined` is because the SDK requires a browser environment at the moment, see #87. You can work around it for now with something like:

``` js
global.window = {
  localStorage: {
    getItem() { return null; },
    setItem() { },
    deleteItem() { }
  }
};
```

**Comment by Patrax** [comment]
I haven't tested it locally under these conditions, but the `global.window= ...` trick worked. Thanks @simonbuchan 

However, I just realized that this would imply a potential security hole because the credentials will not be loaded in the user's window. So, after logging in, I wouldn't be able to request secured resources like this:

```
 AWS.config.credentials.get(function (err) {
    apigClientFactory.newClient({
      accessKey: AWS.config.credentials.accessKeyId, 
      secretKey: AWS.config.credentials.secretAccessKey, 
      sessionToken: AWS.config.credentials.sessionToken,
      region: 'us-east-1'  
    }).userGet( {}, { email : email } )
      .then(function(data){
    ...
```

Meaning that there would be no way to synchronize the window object in Lambda with the window object in the user's browser. Therefore, this is a dead end and I will go back to implementing Cognito straight from the browser.
