### ISSUE TITLE
Error: "window is not defined" throws when authenticateUser() in NodeJs

### ISSUE THREAD

**Issue by kinyat** [aws/amazon-cognito-identity-js#173]
Hi all :)

I am trying to make a user service in lambda which can create and auth(sign in) a user and return an api token back to the client for use in API Gateway (not sure if this is a good approach but just do it anyway :P)

I got an exception "window is not defined" with the following code.

I guess this method is not Backend friendly atm.

``` javascript
import {CognitoUserPool, AuthenticationDetails, CognitoUser} from 'amazon-cognito-identity-js'
import constants from '../constants/constants.json'

export async function signInUser (event, context, cb) {
  const userPool = new CognitoUserPool(constants.cognito.poolData)

  const authenticationData = {
    Username: 'test',
    Password: '12345678'
  }
  const authenticationDetails = new AuthenticationDetails(authenticationData)

  const userData = {
    Username: 'test',
    Pool: userPool
  }
  const cognitoUser = new CognitoUser(userData)

  let result = {}
  try {
    result = await new Promise((resolve, reject) => {
      cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: resolve,
        onFailure: reject
      })
    })
    cb(null, {result, event})
  } catch (error) {
    cb(null, {error, event})
  }
}

```

```
/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ReferenceError: window is not defined
    at e.o.value (/home/eric/development/user-service/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js:19:22615)
    at Response.<anonymous> (/home/eric/development/user-service/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js:19:11223)
    at Request.<anonymous> (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/eric/development/user-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/eric/development/user-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/eric/development/user-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/eric/development/user-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/eric/development/user-service/node_modules/aws-sdk/lib/request.js:668:14)
```

Thanks for all the helps!

**Comment by kinyat** [comment]
"hacked" it by using `node-localstorage` instead. 
Although I don't think it is a good idea but It is working anyway :)

**Comment by fezsteve** [comment]
I've got this also. Is node-localstorage actually working correctly for multiple users? Quick look at the code and suspect it's going to need all the storage ripping out, and the variables passed back to the client.

Am I missing something or does this make the codebase rather useless - beyond a demo? Can't use client-side as would expose all credentials, and can't use server-side.

**Comment by itrestian** [comment]
We will change the behavior such that local storage use should be configurable as described in https://github.com/aws/amazon-cognito-identity-js/issues/87 

If users require local, session, or no storage they will be able to set this.
Please see below for a token storage discussion https://github.com/aws/amazon-cognito-identity-js/issues/21

Server-side, we encourage users to use the ADMIN_NO_SRP_AUTH authentication flow as described in the documentation. This can be used directly with the main AWS SDK.

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html

**Comment by ZwaarContrast** [comment]
Any vision on when this issue will be fixed? Currently faking localstorage to get things to work.

```javascript
const localStorage = {
    getItem: function() { return null; },
};

global.window = {localStorage};
```

**Comment by itrestian** [comment]
This should now be fixed with the recent pull request. Feel free to reopen.
