### ISSUE TITLE
Cannot read property 'Stream' of undefined (var Stream = util.stream.Stream)

### ISSUE THREAD

**Issue by thinkloop** [aws/amazon-cognito-identity-js#203]
Hello,

I am trying to run a minimum cognito example:

```
import { CognitoUserPool } from "amazon-cognito-identity-js";

const userPool = new CognitoUserPool({
  UserPoolId: 'yyyy',
  ClientId: 'xxxxx',
});

userPool.signUp('hi@foo.com', '12345678a', {}, null, (err, result) => {
	if (err) {
		console.log(err);
		return;
	}
	console.log('user name is ' + result.user.getUsername());
	console.log('call result: ' + result);
});

```

When the preceding code runs I receive an error:

```
/workspace/build.js:12376
      var Stream = util.stream.Stream;
                              ^
TypeError: Cannot read property 'Stream' of undefined
    at Object.computeSha256 (/workspace/build.js:12376:31)
    at Request.COMPUTE_SHA256 (/workspace/build.js:6625:18)
    at Request.callListeners (/workspace/build.js:10190:18)
    at Request.emit (/workspace/build.js:10166:10)
    at Request.emit (/workspace/build.js:9590:14)
    at Request.transition (/workspace/build.js:8944:10)
    at AcceptorStateMachine.runTo (/workspace/build.js:11659:12)
    at /workspace/build.js:11671:10
    at Request.<anonymous> (/workspace/build.js:8960:9)
    at Request.<anonymous> (/workspace/build.js:9592:12)
```

To setup the project, I did `npm install --save amazon-cognito-identity-js`, created the file above, then browserified the bundle. 

Looking at other parts of the sdk there are examples of `util.stream` but under the `AWS` namespace: 

```
var Stream = AWS.util.stream.Stream;
```

I wonder if this is related.

Any help appreciated.

**Comment by thinkloop** [comment]
It turns out it had to do with how browserify was building the project, specifically I had `detectGlobals` as `false`, when it should be `true` (I _think_ that's default):

```
browserify $src_js -t [ babelify ] --detectGlobals true 
```

**Comment by patrik-piskay** [comment]
Hi, we are getting the exact same error with Webpack. Any idea how to solve it?

**Comment by thinkloop** [comment]
Cognito proved to have too many gotchas for me, so I ended up rolling my own JWT solution.
