### ISSUE TITLE
1.9.0 has some changed behaviour

### ISSUE THREAD

**Issue by VibyJocke** [aws/amazon-cognito-identity-js#227]
Getting "ReferenceError: window is not defined" when running some jest tests with version 1.9.0, which was not appearing with 1.8.0. Could examine closer if needed.

Complete stacktrace:

ReferenceError: window is not defined

      at Object.e.exports (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:20:589)
      at t (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:649)
      at Object.defineProperty.value (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:9960)
      at t (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:649)
      at Object.<anonymous> (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:20:4395)
      at t (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:649)
      at Object.t.exports (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:1031)
      at t (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:649)
      at t (node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:736)
      at node_modules\amazon-cognito-identity-js\dist\amazon-cognito-identity.min.js:19:741

**Comment by itrestian** [comment]
The recent change shouldn't have impacted that. We were using window localStorage before, did you have a way to get around the absence of window in your tests?

**Comment by VibyJocke** [comment]
No, we didn't need to before (which might be the weird part in the first place).

**Comment by itrestian** [comment]
Yes, this should just fall back to memory storing if window local storage is not available.

https://github.com/aws/amazon-cognito-identity-js/commit/aea20d70710609590159b2e65e9f31f1c4731e86
https://github.com/aws/amazon-cognito-identity-js/commit/48b2086be96011b0a8d2d23da0cf851a304d65d7
