### ISSUE TITLE
Webpack Compile Issue

### ISSUE THREAD

**Issue by fdm20** [aws/amazon-cognito-identity-js#234]
Hello All, I'm new to Amazon Cognito Identity. I'm trying to use it in my React/Redux/Webpack application.

**I'm getting the following Error:**
./~/amazon-cognito-identity-js/~/aws-sdk/apis/cognito-idp-2016-04-18.min.json
Module parse failed: /basic/node_modules/amazon-cognito-identity-js/node_modules/aws-sdk/apis/cognito-idp-2016-04-18.min.json Unexpected token (2:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:11)

**My Code:**

**Signup.js**
```
import {Config, CognitoIdentityCredentials} from "aws-sdk";
import {
  CognitoUserPool,
  CognitoUserAttribute
} from "amazon-cognito-identity-js";
import React from "react";
import ReactDOM from "react-dom";
import appConfig from "./config";

Config.region = appConfig.region;
Config.credentials = new CognitoIdentityCredentials({
  IdentityPoolId: appConfig.IdentityPoolId
});



var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool({
  UserPoolId: "appConfig.UserPoolId",
  ClientId: "j",
});

class SignUpForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
    };
  }

  handleEmailChange(e) {
    this.setState({email: e.target.value});
  }

  handlePasswordChange(e) {
    this.setState({password: e.target.value});
  }

  handleSubmit(e) {
    e.preventDefault();
    const email = this.state.email.trim();
    const password = this.state.password.trim();
    const attributeList = [
      new CognitoUserAttribute({
        Name: 'email',
        Value: email,
      })
    ];
    userPool.signUp(email, password, attributeList, null, (err, result) => {
      if (err) {
        console.log(err);
        return;
      }
      console.log('user name is ' + result.user.getUsername());
      console.log('call result: ' + result);
    });
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit.bind(this)}>
        <input type="text"
               value={this.state.email}
               placeholder="Email"
               onChange={this.handleEmailChange.bind(this)}/>
        <input type="password"
               value={this.state.password}
               placeholder="Password"
               onChange={this.handlePasswordChange.bind(this)}/>
        <input type="submit"/>
      </form>
    );
  }
}

export default SignUpForm

```

**Webpack.config.js**
```
var webpack = require('webpack');

module.exports = {
  devtool: 'inline-source-map',
  entry: [
    'webpack-hot-middleware/client',
    './client/client.js'
  ],
  output: {
    path: 'dist',
    filename: 'bundle.js',
    publicPath: '/'
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['react', 'es2015', 'react-hmre']
        }
      },
         {
        test: /\.json$/,
        loader: 'json'
      }
    ]
      
  }
}
```

**package.json**
```
{
  "name": "react-todo-list",
  "version": "1.0.0",
  "description": "bbhb",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "serve": "nodemon server/server.js --ignore components"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "test",
  "license": "test",
  "dependencies": {
    "amazon-cognito-identity-js": "^1.10.0",
    "aws-sdk": "^2.7.20",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.1.0",
    "express": "^4.14.0",
    "json-loader": "^0.5.4",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-logger": "^2.5.0",
    "redux-thunk": "^1.0.3",
    "webpack": "^1.14.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.14.0"
  },
  "devDependencies": {
    "json-loader": "^0.5.4",
    "webpack": "^1.14.0"
  }
}
```

**Comment by itrestian** [comment]
We haven't experimented with this exact setup but here's a link to a related post 

https://github.com/aws/amazon-cognito-identity-js/issues/123

**Comment by eddanger** [comment]
@fdm20 I had a similar issue when I was setting up webpack in my project to use amazon-cognito-identity-js. I am not sure what the issue was but setting up as babel webpack json file `webpack.config.babel.js` it magically worked. From their example https://github.com/aws/amazon-cognito-identity-js/blob/master/examples/babel-webpack/webpack.config.babel.js

I'd love to know why this is the case.

**Comment by sbussard** [comment]
@fdm20 I copied the snippets into a new folder and I changed the webpack entrypoint to use Signup.js, then I ran `npm install`, then `./node_modules/.bin/webpack`. 

The result was that the only error I got was `Error: Cannot resolve 'file' or 'directory' ./config ...` which is to be expected. Since that file is imported after the cognito library I would've expected to encounter the cognito error first, then the config error.

This, combined with @eddanger's comment, leads me to believe that es6 support might be somehow causing the issue. The version of node that I used was v6.9.1. 

What version of node have you been using to run webpack for this project?

**Comment by sbussard** [comment]
@fdm20 also what operating system are you running this on?

**Comment by fdm20** [comment]
I just checked and I am using node v4.5.0. on OS X El Capitan  10.11.1.

I'll update node now.

**Comment by sbussard** [comment]
@fdm20 did that work?

**Comment by fdm20** [comment]
Thanks for the help! Upgrading cleared many of the errors but I'm still getting a few, below are some of them:
```
ERROR in (webpack)/lib/node/NodeMainTemplateAsync.runtime.js
Module not found: Error: Cannot resolve module 'fs' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/lib/node
 @ (webpack)/lib/node/NodeMainTemplateAsync.runtime.js 9:2-15 24:2-15

ERROR in (webpack)/~/uglify-js/tools/node.js
Module not found: Error: Cannot resolve module 'fs' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/uglify-js/tools
 @ (webpack)/~/uglify-js/tools/node.js 8:9-22

ERROR in (webpack)/lib/node/NodeOutputFileSystem.js
Module not found: Error: Cannot resolve module 'fs' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/lib/node
 @ (webpack)/lib/node/NodeOutputFileSystem.js 5:9-22

ERROR in (webpack)/lib/node/OldNodeWatchFileSystem.js
Module not found: Error: Cannot resolve module 'fs' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/lib/node
 @ (webpack)/lib/node/OldNodeWatchFileSystem.js 5:9-22

ERROR in (webpack)/~/mkdirp/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/mkdirp
 @ (webpack)/~/mkdirp/index.js 2:9-22
```

```
WARNING in ./~/aws-sdk/dist/aws-sdk.js
Critical dependencies:
4:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/aws-sdk/dist/aws-sdk.js 4:113-120

WARNING in (webpack)/~/watchpack/~/chokidar/~/fsevents/fsevents.js
Critical dependencies:
11:13-71 the request of a dependency is an expression
 @ (webpack)/~/watchpack/~/chokidar/~/fsevents/fsevents.js 11:13-71

WARNING in (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/pre-binding.js
Critical dependencies:
19:22-48 the request of a dependency is an expression
 @ (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/pre-binding.js 19:22-48

WARNING in (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/util/versioning.js
Critical dependencies:
15:20-67 the request of a dependency is an expression
 @ (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/util/versioning.js 15:20-67

WARNING in (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Cannot resolve module 'npm' in /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util
 @ (webpack)/~/watchpack/~/chokidar/~/fsevents/~/node-pre-gyp/lib/util/compile.js 39:27-49

WARNING in (webpack)/~/watchpack/~/chokidar/~/fsevents/ISSUE_TEMPLATE.md
Module parse failed: /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/ISSUE_TEMPLATE.md Unexpected token (1:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:3)
    at Parser.pp$4.raise (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/freddrickmorrow/Desktop/FredM/react-todo-list-part-12-start_OLD/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 @ (webpack)/~/watchpack/~/chokidar/~/fsevents ^\.\/.*$

```

**Comment by itrestian** [comment]
This was probably related to Webpack support in the main aws sdk at that point.

https://github.com/aws/aws-sdk-js/issues/1341
