### ISSUE TITLE
Facebook login fails - Error: Missing required key 'IdentityId' in params 

### ISSUE THREAD

**Issue by wolfmanfx** [aws/amazon-cognito-identity-js#465]
Hi,
I did a repost of this because I think i belongs to this repo.

After getting the fb accesstoken I do this ->
   
```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: aws_cognito_identity_pool_id,
            Logins:  { 'graph.facebook.com': response.authResponse.accessToken}
            }, {
              region: aws_cognito_region
          });
```

          AWS.config.credentials.get(function(e){
            console.log(e);
            resolve();
          });`

I takes a very long time (almost 1 minute) to give me the following the error ->

`Error: Missing required key 'IdentityId' in params
code:"MissingRequiredParameter"
message:"Missing required key 'IdentityId' in params"
name:"MissingRequiredParameter"
stack:"MissingRequiredParameter: Missing required key 'IdentityId' in params\n    at constructor.fail (http://localhost:8000/assets/aws-sdk.min.js:41:23483)\n    at constructor.validateStructure (http://localhost:8000/assets/aws-sdk.min.js:41:23693)\n    at constructor.validateMember (http://localhost:8000/assets/aws-sdk.min.js:41:24069)\n    at constructor.validate (http://localhost:8000/assets/aws-sdk.min.js:41:23139)\n    at constructor.<anonymous> (http://localhost:8000/assets/aws-sdk.min.js:41:957)\n    at constructor.callListeners (http://localhost:8000/assets/aws-sdk.min.js:42:27867)\n    at constructor.emit (http://localhost:8000/assets/aws-sdk.min.js:42:27578)\n    at constructor.emitEvent (http://localhost:8000/assets/aws-sdk.min.js:42:13684)\n    at constructor.e (http://localhost:8000/assets/aws-sdk.min.js:42:9341)\n    at a.runTo (http://localhost:8000/assets/aws-sdk.min.js:44:5201)"
time:Wed Jul 05 2017 07:13:26 GMT+0200 (CEST) {}`

I already updated the aws-sdk to the latest one but still the same error. Furthermore the login via email works but its slow like hell. Any advise or help?

**Comment by itrestian** [comment]
What environment are you using this in?

Can you try this with the unminified versions of the script and Google Chrome Developer Tools to get a more descriptive error?
